name: 同步上游仓库
# File: .github/workflows/iEwha-sync.yml

on:
  schedule:
  - cron:  "5 */12 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: iEwha-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/iEwha/QuantumultX.git"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.PAT }}
